### PR TITLE
Add handler when job is a success so it's easier to add custom logging / monitoring

### PR DESCRIPTION
**Pull request by archiloque**

### CODE REVIEW

**Comment by senny** [comment]
I'd rather not expand the worker interface for trivial cases like this. We already have `call(job)`. This can easily be implemented as:

```ruby
class MyWorker
  def call(job)
    super
    # success
  end
end
```

I take this PR as an opportunity to make some fundamentals of how I see QC clear.

QC is designed as a minimal foundation to get a queuing system with PG as a backend going. It's intended to be highly hackable by developers to customize it for their own needs. This means that:
* It's expected that you will read the source code of QueueClassic
* It's expected that you will write your own code to make QueueClassic fit your needs
* It's not expected to provide every use-case out of the box.
* It's expected that foundation provided by QC is minimal and extendable.

/cc @smathieu @jipiboily 

For the reasons presented above, I don't see the need for this hook.

**Comment by jipiboily** [comment]
I totally agree with @senny's vision here. Should we add that to the README under `What is queue_classic?` maybe?

**Comment by archiloque** [comment]
I agree it can be achieved by overriding call but it's strange to have a callback for error and not for success.

**Comment by senny** [comment]
@archiloque I disagree. The error callback has to be there because it's hard to hook into that flow otherwise. In the case of success the use-cases vary a lot. For example, my apps almost always require an around filter for successful jobs. Basically this means that I have to overwrite `call`. Introducing methods like `before_run` and `handle_success` makes things more complicated without any real gain.

**Pull request closed without merging**
