### PR TITLE
turn job into a class

### PR DESCRIPTION
**Pull request by archiloque**

### CODE REVIEW

**Comment by smathieu** [comment]
Can you please provide more details about what problem you're hoping this will solve?

**Comment by archiloque** [comment]
For my project I need to subclass Worker to add custom behavior, and using a class for the Job makes the contact easier to understand than with a Hash. I ask @senny about the idea and he suggested to do a PR to discuss about it.

**Comment by smathieu** [comment]
I'd like to know exactly what is it you're trying to achieve. One problem with this approach is that it breaks API compatibility. If we we're to release this change, this would require a major version bump.

**Comment by senny** [comment]
@archiloque as stated in my emails I am not in favor of this change unless it enables something. As it stands now this introduces needless API breakage and doesn't add much to the table.

**Comment by archiloque** [comment]
@smathieu what I want is to make easier to overload methods in Worker as in the example you provide in the README. Currently as job is a Hash we must have a look at the code to know what the fields are and what they contain, by transforming it into a class it make it easier.

**Comment by jipiboily** [comment]
I'm on the same page as @smathieu and @senny here. I don't see much added value, not enough to break the API. Sorry.

Thanks for the proposal and the time you spent doing it!

**Comment by archiloque** [comment]
No problem, thanks for your time! A last question : in this case would you be interested by a more detailled example in the README ?

**Comment by smathieu** [comment]
@archiloque Absolutely.

**Comment by jipiboily** [comment]
@archiloque sure thing! Out of curiosity, can you tell me what you found out that was missing in the example?

**Pull request closed without merging**
