### PR TITLE
Don't rescue Time.now exceptions in log_yield

### PR DESCRIPTION
**Pull request by shosti**
Fixes QueueClassic/queue_classic#268

### CODE REVIEW

**Comment by jipiboily** [comment]
@shosti that's really weird! @senny, seen that before?

Could you add a test for that please so we don't have a regression?

**Comment by senny** [comment]
nope, never. Although we do not run with Ruby 2.3.0 in production.

**Comment by senny** [comment]
@jipiboily don't think there's a sane way to prevent regressions on that. `Time.now` should not raise any errors.

**Comment by senny** [comment]
@shosti `TypeError: can't convert nil into an exact number` seems to be the follow up error in the ensure block. Do you have any idea what the actual exception from `Time.now` looks like?

**Comment by shosti** [comment]
Nope, haven't run the updated code yet in prod. I'll let you know what I find out 😉.

**Comment by senny** [comment]
@shosti thanks.

**Pull request merged**
